# Generated by Django 5.1.5 on 2025-02-27 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Device',
            new_name='Site',
        ),
    ]
