# Generated by Django 5.1.5 on 2025-03-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_device_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='instance_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='site',
            name='last_connected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ws_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='HomeAssistantInstance',
        ),
    ]
