# Generated by Django 5.1.5 on 2025-03-29 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_site_instance_id_site_last_connected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='instance_id',
            new_name='site_id',
        ),
    ]
